### ISSUE TITLE
Add train and test error

### ISSUE THREAD

**Issue by fses91** [reiinakano/xcessiv#54]
Hi, it would be nice to display train and test error so we can evaluate easier if a model is overfitting. 
Very nice work so far.
Thanks

**Comment by reiinakano** [comment]
Any "error" or metric displayed is calculated based on cross validation, which you can think of as a more robust form of getting the test error. If you just wanted the test error, you can set the number of folds to 1. Sadly right now there is no way to see the train error but that is by design as I have not found it very useful.
